"""Every endpoint must actually be called by at least one test.

Line coverage alone is not enough for this: a route can be exercised by a test
that checks something else entirely. This test counts real calls -- it turns
red as soon as someone adds a route without testing it.

The reason this exists: the home page was missing entirely, even though login,
logout, and navigation all pointed to it. No test had ever called it.
"""

import re

import pytest

from tests.helpers import alle_api_routen
from thermoctl.app import create_app

# Generated by FastAPI itself, not written by us. `/docs` is deliberately NOT
# listed here any more: we have served the interface ourselves since it was
# bundled locally, so it must be checked like any other page.
NOT_OURS = {"/openapi.json"}


def _our_routes() -> set[tuple[str, str]]:
    pairs: set[tuple[str, str]] = set()
    for route in alle_api_routen(create_app()):
        if route.path in NOT_OURS:
            continue
        for method in route.methods - {"HEAD", "OPTIONS"}:
            pairs.add((method, route.path))
    return pairs


def _as_pattern(path: str) -> re.Pattern[str]:
    """Turns `/api/v1/zones/{zone_id}` into a pattern that matches `/api/v1/zones/7`."""
    return re.compile("^" + re.sub(r"\{[^}]+\}", r"[^/]+", path) + "$")


@pytest.fixture(scope="session")
def called_endpoints(request: pytest.FixtureRequest) -> set[tuple[str, str]]:
    return getattr(request.config, "_called_endpoints", set())


def test_every_endpoint_is_called_in_some_test(
    called_endpoints: set[tuple[str, str]],
    request: pytest.FixtureRequest,
) -> None:
    # The record is built up over the course of the run. Running only this file
    # sees an almost empty record and would otherwise raise a false alarm about
    # every endpoint in the project.
    if len(request.session.items) < 50:
        pytest.skip("only meaningful in a full test run")

    unchecked = []
    for method, path in sorted(_our_routes()):
        pattern = _as_pattern(path)
        if not any(m == method and pattern.match(p) for m, p in called_endpoints):
            unchecked.append(f"{method} {path}")
    assert not unchecked, (
        "No test calls these endpoints: " + ", ".join(unchecked)
    )
