import re
from datetime import datetime
from decimal import Decimal
from pathlib import Path

from fastapi import Request
from fastapi.templating import Jinja2Templates
from jinja2 import Environment, FileSystemLoader
from jinja2.ext import Extension

from thermoctl.auth.csrf import csrf_token
from thermoctl.auth.sessions import COOKIE_NAME
from thermoctl.config import get_settings
from thermoctl.db.base import utcnow
from thermoctl.domain.time import local_time

TEMPLATES_DIR = Path(__file__).parent / "templates"


class _CsrfFormExtension(Extension):
    """Give every mutating HTML form a non-JavaScript CSRF fallback.

    HTMX adds the token as a header, but an ordinary browser submission can only
    send controls contained in the form.  Doing this while templates are loaded
    protects all present and future POST forms, including forms generated by
    macros.  Forms which need a different token (the kiosk) or already carry an
    explicit field are left untouched.
    """

    _FORM = re.compile(r"(<form\b[^>]*>)(.*?</form>)", re.DOTALL | re.IGNORECASE)
    _POST_METHOD = re.compile(
        r"\bmethod\s*=\s*(?:(['\"])post\1|post(?=\s|>))", re.IGNORECASE
    )
    _HTMX_POST = re.compile(r"\bhx-post(?:\s*=|\s|>)", re.IGNORECASE)
    _CSRF_FIELD = 'name="csrf_token"'

    def preprocess(self, source: str, name: str | None, filename: str | None = None) -> str:
        def add_field(match: re.Match[str]) -> str:
            opening_tag = match.group(1)
            if not (self._POST_METHOD.search(opening_tag) or self._HTMX_POST.search(opening_tag)):
                return match.group(0)
            if self._CSRF_FIELD in match.group(0):
                return match.group(0)
            field = (
                '<input type="hidden" name="csrf_token" value="{{ session_csrf }}">'
            )
            return f"{match.group(1)}\n{field}{match.group(2)}"

        return self._FORM.sub(add_field, source)


def _logged_in_user(request: Request) -> dict[str, object]:
    """Provides every template with the logged-in user.

    Without this, the top bar on the start page carried the name and everywhere else
    the word "account" -- the start page was the only view that put `user` into
    its context. A control that is named differently depending on the page looks like
    a different control.

    The user is not resolved again: the login has already determined it anyway and
    stored it under `request.state`. If it's missing there, simply nothing shows --
    the login page has none.
    """
    session_secret = request.cookies.get(COOKIE_NAME)
    session_csrf = (
        csrf_token(session_secret, get_settings().secret_key.get_secret_value())
        if session_secret is not None
        else ""
    )
    return {
        "top_bar_user": getattr(request.state, "user", None),
        "session_csrf": session_csrf,
    }


templates = Jinja2Templates(
    env=Environment(
        loader=FileSystemLoader(str(TEMPLATES_DIR)),
        autoescape=True,
        extensions=[_CsrfFormExtension],
    ),
    context_processors=[_logged_in_user],
)

# Bootstrap and HTMX sit as files in this directory (see static/HERKUNFT.md) and
# are served locally, not via a CDN -- `thermoctl` should stay usable on a home
# network without internet access, too.
STATIC_DIR = Path(__file__).parent / "static"


def is_partial_swap(request: Request) -> bool:
    """Whether htmx is only loading a piece of the page -- and not fetching a whole page.

    `HX-Request` alone is **not** enough for this: ever since `hx-boost="true"` has
    been on the <body>, every ordinary navigation carries this header too. As a
    result, six views rendered only their content without the frame -- whoever went to
    /geraete or /audit via the menu lost the top bar and could only get it back by
    reloading. On a direct call to the same address everything was fine, which is why
    nobody noticed who simply opened the page to check it.

    `HX-Boosted` is additionally set by htmx when the request comes from a boosted
    link. It's only truly a partial swap without this header.
    """
    return "HX-Request" in request.headers and "HX-Boosted" not in request.headers


def age_in_words(moment: datetime | None, now: datetime | None = None) -> str:
    """How long ago something was, in words — 'vor 3 Minuten' instead of a timestamp.

    For a heating control this is exactly the question: is this reading fresh, or has
    it been sitting there since yesterday? A raw timestamp with microseconds doesn't
    answer that, it demands mental arithmetic — and when in doubt, you get it wrong.

    All points in time are naive UTC, as throughout the whole project.
    """
    if moment is None:
        return "noch nie"
    elapsed = ((now or utcnow()) - moment).total_seconds()
    if elapsed < 0:
        # A slightly misconfigured sensor must not display 'in -3 minutes'.
        return "gerade eben"
    for limit, divisor, singular, plural in (
        (60, 1, "Sekunde", "Sekunden"),
        (3600, 60, "Minute", "Minuten"),
        (86400, 3600, "Stunde", "Stunden"),
    ):
        if elapsed < limit:
            value = int(elapsed // divisor)
            return f"vor {value} {singular if value == 1 else plural}"
    days = int(elapsed // 86400)
    return f"vor {days} {'Tag' if days == 1 else 'Tagen'}"


# The range over which temperatures are rendered as color. Not the input's limits,
# but the range in which living-room temperatures actually move -- otherwise
# everything would sit in the same pale middle.
SPUR_KALT = Decimal("15")
SPUR_WARM = Decimal("23")


def warmth_fraction(temperature: Decimal | None) -> float:
    """0 = coldest representable setpoint, 1 = warmest. Clamped outside that range.

    Lives here and not in either of the two views: the start page and the week view
    show the same quantity, and two scales for the same statement would be two scales
    that drift apart.
    """
    if temperature is None:
        return 0.5
    fraction = (temperature - SPUR_KALT) / (SPUR_WARM - SPUR_KALT)
    return float(min(max(fraction, Decimal(0)), Decimal(1)))


def grad(value: Decimal | float | None, digits: int = 1) -> str:
    """A temperature written the way it's done in German: with a comma.

    Display only. A comma has no business in `value` attributes of
    `<input type="number">` -- the browser then silently discards the value, and the
    field sits there empty with nobody able to say why.
    """
    if value is None:
        return "–"
    return f"{value:.{digits}f}".replace(".", ",")


templates.env.filters["age"] = age_in_words
templates.env.filters["grad"] = grad
templates.env.filters["localtime"] = local_time
