"""Die Stammtabelle der Umbenennung.

Zusammengesetzt statt Name fuer Name: `zonenname` -> `zone_name`, `geraet_id` ->
`device_id`. Das haelt die Benennung ueber 750 Bezeichner hinweg gleich -- von Hand
hiesse dieselbe Vokabel in jeder Datei anders.

Die Reihenfolge zaehlt: Laengere Staemme zuerst, sonst frisst `zone` das `zonen` in
`zonenzustand`.
"""

# Bezeichner, die schon englisch sind und die die Suche nur zufaellig getroffen hat.
UNVERAENDERT = {
    "zone", "zones", "zone_id", "zone_ids", "zone_obj", "zone_a", "zone_b",
    "temperature_c", "temperature_offset_k", "temperature_source_device_id",
    "timezone", "starts_at", "is_zone_scoped", "frost_protection_mode_id",
    "visible_zones", "Zone", "ZoneDevice", "ZoneOverride", "ZoneSetpoint", "ZoneState",
    "in_schalter", "pytest_collection_modifyitems", "hersteller",
}

# Ganze Namen, die zusammengesetzt nicht gut herauskommen.
EINZELN = {
    "antwort": "response", "_antwort": "_response", "_Antwort": "_Response",
    "ergebnis": "result", "ergebnisse": "results", "mqtt_ergebnis": "mqtt_result",
    "meross_ergebnis": "meross_result",
    "klartext": "plaintext", "_klartext": "_plaintext",
    "eintrag": "entry", "_eintrag": "_entry", "eintraege": "entries",
    "wert": "value", "werte": "values", "_wert": "_value", "_werte": "_values",
    "rohwert": "raw_value", "rohwerte": "raw_values", "hash_wert": "hash_value",
    "cookie_wert": "cookie_value", "zonenwert": "zone_value",
    "ausgangswert": "initial_value", "vorheriger_wert": "previous_value",
    "kontaktwert": "contact_value", "hoechstwert": "maximum",
    "jetzt": "now", "JETZT": "NOW", "jetzt_utc": "now_utc",
    "art": "kind", "art_id": "kind_id", "arten": "kinds",
    "fehler": "errors", "_fehler": "_errors", "feldfehler": "field_errors",
    "formular": "form", "formularwerte": "form_values", "_formularwerte": "_form_values",
    "rohschritt": "raw_step", "schritt": "step", "schritt_k": "step_k",
    "muster": "pattern", "_MUSTER": "_PATTERN", "_als_muster": "_as_pattern",
    "treffer": "match", "stand": "state", "start": "start", "erst": "first",
    "erste": "first", "erster": "first", "letzter": "last", "letzte": "last",
    "zuletzt": "last_seen", "zuerst": "first", "naechster": "next_one",
    "liste": "items", "_Liste": "_List", "anzahl": "count", "zaehler": "counter",
    "zaehlend": "counting", "grenze": "limit", "grenzen": "limits",
    "GRENZEN": "LIMITS", "hoechstabstand": "maximum_interval",
    "abstand": "interval", "dauer": "duration", "dauer_s": "duration_s",
    "dauer_minuten": "duration_minutes", "als_dauer": "as_duration",
    "_dauertext": "_duration_text", "alter": "age", "alter_s": "age_s",
    "alter_in_worten": "age_in_words", "_alter_in_worten": "_age_in_words",
    "zeitpunkt": "moment", "_zeitpunkt": "_moment", "zeitpunkte": "moments",
    "zeitzone": "timezone_name", "verstrichen": "elapsed", "gewartet": "waited",
    "gelesen": "read_back", "gespeichert": "stored", "geprueft": "checked",
    "geaendert": "changed", "erwartet": "expected", "erwartet_json": "expected_json",
    "gestartet": "started", "ungeprueft": "unchecked", "sichere_werte": "safe_values",
    "standard": "default", "vorgabe": "default", "vorgaben": "defaults",
    "_vorgaben": "_defaults", "kennung": "identifier", "_kennung": "_identifier",
    "vorherige_kennung": "previous_identifier",
    "bezeichnung": "label", "beschriftung": "label", "_beschriftung": "_label",
    "BESCHRIFTUNG": "LABELS", "_beschriften": "_label_for",
    "marke": "marker", "zweite_marke": "second_marker", "bild": "picture",
    "bilder": "pictures", "_bild": "_picture", "modul": "module",
    "werkzeuge": "tools", "abschnitt": "segment", "abschnitte": "segments",
    "nachricht": "message", "nachrichten": "messages", "_nachrichten": "_messages",
    "bewertung": "assessment", "verstoesse": "violations", "hilfe": "helper",
    "lesen": "read_only", "nur_lesen": "read_only", "schalten": "switching",
    "geschaltet": "switched", "schaltet": "switches", "laufend": "running",
    "laufen": "run", "lauf": "run", "_lauf": "_run", "warten": "wait",
    "zyklus": "cycle", "zyklus_sekunden": "cycle_seconds", "ablauf": "expiry",
    "folgetag": "next_day", "tage": "days", "tag": "day", "nacht": "night",
    "woche": "week", "_woche": "_week", "wochenanfang": "week_start",
    "tagesanfang": "day_start", "nach_tag": "by_day", "erste_zeilen": "first_rows",
    "filterwerte": "filter_values", "zustandssatz": "state_row",
    "modul": "module", "gruppe2": "second_group", "zweite_gruppe": "second_group",
    "zweite_zone": "second_zone", "web_zone": "web_zone", "alt_geraet": "old_device",
    "frisch_geraet": "fresh_device", "batteriegeraet": "battery_device",
    "nachher_erreichbar": "reachable_after", "vorher_erreichbar": "reachable_before",
    "erreichbar": "reachable", "erreichbarkeit": "availability",
    "verfuegbarkeits_topic": "availability_topic",
    "montag_drei_uhr": "monday_three", "montag_zehn_uhr": "monday_ten",
    "MONTAG_ACHT": "MONDAY_EIGHT", "nachtstunden": "night_hours",
    "nachtstunden_lesen": "read_night_hours", "_stunde_lesen": "_read_hour",
    "ueber_temperatur": "above_temperature", "hysterese": "hysteresis",
    "mindestdauer": "minimum_duration", "loeschsperre": "delete_guard",
    "in_schalter": "inside_switch", "quellpunkte": "source_points",
    "quellzone": "source_zone", "zielpunkte": "target_points",
    "andere_quelle": "other_source", "tausch": "swap", "_bestand": "_inventory",
    "verwalter": "administrator", "_letzter_verwalter": "_last_administrator",
    "VERWALTUNGSRECHT": "ADMIN_PERMISSION", "Verwaltungsfehler": "AdministrationError",
    "auditliste": "audit_list", "ANMELDUNG": "LOGIN", "anmeldung": "login",
    "anmelde": "login", "anmelden": "log_in", "_anmelden": "_log_in",
    "nach_der_anmeldung": "after_login", "vor_der_anmeldung": "before_login",
    "_angemeldeter_benutzer": "_logged_in_user", "_eigener_benutzer": "_own_user",
    "sitzung": "http_session", "_sitzung": "_http_session",
    "_Sitzungen": "_Sessions", "_fremde_sitzung": "_foreign_session",
    "sitzung_geheimnis": "session_secret", "sitzungsdauer_s": "session_lifetime_s",
    "sitzungslebensdauer_s": "session_lifetime_s",
    "lebensdauer_s": "lifetime_s", "STANDARD_SITZUNGS_LEBENSDAUER_S":
        "DEFAULT_SESSION_LIFETIME_S",
    "bruecke": "bridge", "brueckenmeldung": "bridge_notice",
    "bruecke_erreichbar": "bridge_reachable", "BRUECKENZUSTAND": "BRIDGE_STATE",
    "stoerung": "fault", "Stoerungsmeldung": "FaultNotice",
    "senden": "send", "veroeffentlichen": "publish", "veroeffentlicht": "published",
    "veroeffentlicher": "publisher", "senden_erlaubt": "sending_allowed",
    "scharf": "armed", "_scharf": "_armed", "scharf_schalten": "arm",
    "scharfschalten": "arm", "ScharfSchalten": "Arm", "scharf_topic": "armed_topic",
    "scharf_anmeldung": "armed_discovery", "schalten_erlaubt": "switching_allowed",
    "_schalten_erlaubt": "_switching_allowed",
    "trockenlauf_erzwingen": "force_dry_run",
    "begruendung": "reason", "gueltig_tage": "valid_days",
    "hoechstwert": "maximum", "zonenbezogen": "zone_scoped",
    "_zonenbezogen": "_zone_scoped", "ausser_zone_id": "except_zone_id",
    "punkte_je_zone": "points_per_zone", "nach_zone": "by_zone",
    "nach_geraet": "by_device", "ohne_zone": "without_zone",
    "ohne_recht": "without_permission", "mit_recht": "with_permission",
    "ohne_zustand": "without_state", "start_zustand": "start_state",
    "alter_zustand": "old_state", "mqtt_zustand": "mqtt_state",
    "gesunder_zustand": "healthy_state", "kranker_zustand": "unhealthy_state",
    "_beispielzustand": "_example_state", "sensorzustand": "sensor_state",
    "zonenzustand": "zone_state", "vorheriger_wert": "previous_value",
    "_vorheriger_zustand": "_previous_state", "_vorheriger_wert": "_previous_value",
    "stille_faehigkeiten": "quiet_capabilities", "zuletzt_gehoert": "last_heard",
    "zuletzt_gesehen": "last_seen", "zuletzt_geschlossen": "last_closed",
    "zuletzt_gedrueckt": "last_pressed", "_zuletzt_gedrueckt": "_last_pressed",
    "belegung": "binding", "belegung_setzen": "set_binding", "Belegung": "Binding",
    "taste_belegen": "bind_button", "_bedienbefehle": "_controller_commands",
    "aktoren": "actuators", "aktor": "actuator", "Aktor": "Actuator",
    "kontakt": "contact", "fensterkontakte": "window_contacts",
    "fenster_offen": "window_open", "_fenster_offen": "_window_open",
    "_fensterlage": "_window_situation", "fenster_zu_seit_s": "window_closed_for_s",
    "fensterrolle": "window_role", "_sicherstellen_offen": "_ensure_open",
    "frost": "frost", "frost_c": "frost_c", "frost_code": "frost_code",
    "frost_id": "frost_id", "frost_temp": "frost_temp", "frostschutz": "frost_protection",
    "_frostschutz_sollwert": "_frost_setpoint",
    "_FROSTSCHUTZ_STANDARD": "_FROST_DEFAULT",
    "messwert": "measurement", "messwert_anlegen": "create_measurement",
    "alte_messwerte_loeschen": "delete_old_measurements",
    "_messzeitpunkt": "_measured_at", "beobachtung": "reading",
    "beobachtungen": "readings", "Beobachtung": "Reading",
    "AltsystemBeobachtung": "LegacyReading",
    "beobachtungen_aus_nutzlast": "readings_from_payload",
    "beobachtung_aus_topic": "reading_from_topic",
    "nutzlast": "payload", "_nutzlast": "_payload",
    "temperatur": "temperature", "temperatur_c": "temperature_c",
    "temperaturen": "temperatures", "temperatur_text": "temperature_text",
    "_temperatur_text": "_temperature_text",
    "temperatur_pruefen": "check_temperature",
    "temperatur_fuer_modus": "temperature_for_mode",
    "MINDESTTEMPERATUR_C": "MINIMUM_TEMPERATURE_C",
    "HOECHSTTEMPERATUR_C": "MAXIMUM_TEMPERATURE_C",
    "THERMOSTATSCHRITT": "THERMOSTAT_STEP",
    "STANDARDSCHRITT_K": "DEFAULT_STEP_K",
    "ist_temperatur": "current_temperature",
    "uhrzeit": "time_of_day", "uhrzeit_in_minuten": "time_of_day_in_minutes",
    "wochentag": "weekday", "startminute": "start_minute",
    "MINUTEN_JE_WOCHE": "MINUTES_PER_WEEK", "MINUTEN_PRO_TAG": "MINUTES_PER_DAY",
    "STUNDEN_JE_TAG": "HOURS_PER_DAY", "TAGE_JE_WOCHE": "DAYS_PER_WEEK",
    "WOCHENTAGE": "WEEKDAYS", "_TAGE": "_DAYS", "LUECKENFAKTOR": "GAP_FACTOR",
    "wochenabschnitte": "week_segments", "wochenbild": "week_picture",
    "_wochenminute": "_week_minute", "_punktminute": "_point_minute",
    "_tagesspur": "_day_track", "Tagesabschnitt": "DaySegment",
    "Tageswert": "DayValue", "Zonenstatistik": "ZoneStatistics",
    "anlagenbild": "plant_diagram", "Anlagenbild": "PlantDiagram",
    "Geraetebild": "DevicePicture", "Zonenbild": "ZonePicture",
    "schnittstellen": "interfaces", "Schnittstelle": "Interface",
    "abdeckung": "coverage", "aufgerufene_endpunkte": "called_endpoints",
    "_aufgerufene_endpunkte": "_called_endpoints",
    "_endpunkte_mitschreiben": "_record_endpoints",
    "_aendernde_routen": "_writing_routes",
    "AENDERNDE_METHODEN": "WRITING_METHODS",
    "AENDERNDE_UND_LESENDE": "WRITING_AND_READING",
    "klartext": "plaintext", "verschiebefehler": "move_error",
    "_haette_nicht_starten_duerfen": "_should_not_have_started",
    "_ohne_echte_wartezeit": "_without_real_waiting",
    "_erster_versuch_scheitert": "_first_attempt_fails",
    "_HaengenderStrom": "_HangingStream", "Nachrichtenstrom": "MessageStream",
    "_umgebung_fuer_die_ganze_sitzung": "_environment_for_the_whole_session",
    "_ohne_diese_gruppe_kein_verwalter": "_without_this_group_no_administrator",
    "CONSTRAINT_FEHLER": "CONSTRAINT_ERRORS",
    "_FEHLERMELDUNG": "_ERROR_MESSAGE",
    "_ANFRAGE_ID_MUSTER": "_REQUEST_ID_PATTERN",
    "_laufende_meldungen": "_running_notices",
    "_webhook_senden": "_send_webhook",
    "_warnen_wenn_ungeschuetzt_erreichbar": "_warn_if_reachable_unprotected",
    "geraetename_mit_umlaut_und_leerzeichen": "device_name_with_umlaut_and_space",
    "_geraetename": "_device_name", "geraetename": "device_name",
    "geraetenamen": "device_names", "_geraetenamen": "_device_names",
    "zonenname": "zone_name", "_zonenname": "_zone_name",
    "zonennamen": "zone_names", "_weiterer_zonenname": "_another_zone_name",
    "modusname": "mode_name", "modusnamen": "mode_names", "modus_name": "mode_name",
    "befehl_name": "command_name", "quelle_code": "source_code_value",
    "quellen_code": "source_codes", "modus_code": "mode_code",
    "befehl_code": "command_code",
}

# Zusammensetzbare Staemme. Laenge zuerst -- sonst frisst `zone` das `zonen` in
# `zonenzustand`, und `modus` das `modi`.
STAMM: list[tuple[str, str]] = [
    ("zeitplanpunkt", "schedule_point"), ("schaltpunkt", "schedule_point"),
    ("zeitplan", "schedule"), ("uebersteuerung", "override"), ("uebersteuer", "override"),
    ("betriebsart", "operating_mode"), ("regelparameter", "control_parameters"),
    ("bediengeraet", "controller"), ("geraetezustand", "device_state"),
    ("geraeteliste", "device_list"), ("geraeteschau", "device_survey"),
    ("geraeteklassen", "device_classes"), ("geraetezuordnung", "device_assignment"),
    ("geraete", "devices"), ("geraet", "device"),
    ("messquelle", "temperature_source"), ("sollwert", "setpoint"),
    ("schattenentscheidung", "shadow_decision"), ("schatten", "shadow"),
    ("veroeffentlichung", "publication"), ("veroeffentlich", "publish"),
    ("einstellung", "setting"), ("benutzer", "user"), ("gruppe", "group"),
    ("gruppen", "group"), ("recht", "permission"), ("berechtigung", "permission"),
    ("faehigkeit", "capability"), ("anbindung", "integration"),
    ("zuordnung", "assignment"), ("nachricht", "message"), ("befehl", "command"),
    ("zustand", "state"), ("quelle", "source"), ("punkt", "point"),
    ("modus", "mode"), ("modi", "modes"), ("zonen", "zone"), ("zone", "zone"),
    ("steuerung", "control"), ("regelung", "control_loop"), ("regel", "control"),
    ("schnittstelle", "interface"), ("statistik", "statistics"),
    ("passwort", "password"), ("token", "token"), ("audit", "audit"),
    ("setup", "setup"), ("parameter", "parameter"), ("thermostat", "thermostat"),
    ("boost", "boost"), ("mcp", "mcp"), ("web", "web"), ("meross", "meross"),
    ("mqtt", "mqtt"), ("csrf", "csrf"), ("passkey", "passkey"),
    ("discovery", "discovery"), ("topic", "topic"), ("cookie", "cookie"),
    ("principal", "principal"), ("client", "client"), ("json", "json"),
]

# Wortteile, die als Vor- oder Nachsilbe vorkommen.
TEIL: list[tuple[str, str]] = [
    ("_anlegen", "_create"), ("_erstellen", "_create"), ("_speichern", "_save"),
    ("_aendern", "_update"), ("_loeschen", "_delete"), ("_entfernen", "_remove"),
    ("_setzen", "_set"), ("_lesen", "_read"), ("_pruefen", "_check"),
    ("_auflisten", "_list"), ("_verarbeiten", "_process"), ("_verschieben", "_move"),
    ("_uebernehmen", "_adopt"), ("_ausfuehren", "_execute"), ("_abmelden", "_deregister"),
    ("_anmeldung", "_discovery"), ("_anmelden", "_register"), ("_erklaeren", "_explain"),
    ("_aufheben", "_cancel"), ("_beenden", "_end"), ("_tauschen", "_swap"),
    ("_loesen", "_detach"), ("_zuordnen", "_assign"), ("_fortschreiben", "_advance"),
    ("_bearbeiten", "_edit"), ("_anzeigen", "_show"), ("_widerrufen", "_revoke"),
    ("_abschliessen", "_finish"), ("_beginnen", "_begin"), ("_aufloesen", "_resolve"),
    ("_vergeben", "_grant"), ("_entziehen", "_revoke"), ("_erzwingen", "_force"),
    ("_ansicht", "_view"), ("_formular", "_form"), ("_seite", "_page"),
    ("_liste", "_list"), ("_uebersicht", "_overview"), ("_antworten", "_responses"),
    ("_fehler", "_error"), ("_werte", "_values"), ("_wert", "_value"),
    ("_name", "_name"), ("_id", "_id"), ("_ids", "_ids"), ("_code", "_code"),
    ("_topics", "_topics"), ("_topic", "_topic"), ("_setzen_view", "_set_view"),
    ("aufgeloester_", "resolved_"), ("geltender_", "current_"),
    ("naechster_", "next_"), ("naechste_", "next_"), ("alte_", "old_"),
    ("alter_", "old_"), ("neue_", "new_"), ("fremde_", "foreign_"),
    ("fremder_", "foreign_"), ("sichtbare_", "visible_"), ("eigene_", "own_"),
    ("gepruefte_", "checked_"), ("erforderliche_", "required_"),
]

# Klassennamen werden ausgeschrieben und nicht zusammengesetzt: Eine Ersetzung, die
# Gross- und Kleinschreibung ignoriert, macht aus `ZoneAntwort` ein `zoneAntwort` --
# und aus `ZoneInfo` der Standardbibliothek beinahe dasselbe.
KLASSEN = {
    "AltsystemBeobachtung": "LegacyReading",
    "Anlagenbild": "PlantDiagram",
    "Bediengeraetefehler": "ControllerError",
    "Befehl": "Command",
    "BefehlsTopics": "CommandTopics",
    "Befehlsfehler": "CommandError",
    "Belegung": "Binding",
    "Beobachtung": "Reading",
    "Betriebsartunbekannt": "UnknownOperatingMode",
    "BoostAntwort": "BoostResponse",
    "DiscoveryNachricht": "DiscoveryMessage",
    "Domaenenfehler": "DomainError",
    "FaehigkeitFehlt": "CapabilityMissing",
    "Fernbedienungsfehler": "RemoteControlError",
    "Formularfehler": "FormError",
    "GeraetAntwort": "DeviceResponse",
    "Geraetebeschreibung": "DeviceDescription",
    "Geraetebild": "DevicePicture",
    "Geraeteschau": "DeviceSurvey",
    "HttpAntwort": "HttpResponse",
    "MerossSchalter": "MerossSwitch",
    "ModusAnlegen": "CreateMode",
    "ModusAntwort": "ModeResponse",
    "MqttVeroeffentlicher": "MqttPublisher",
    "Nachricht": "Message",
    "Nachrichtenart": "MessageKind",
    "Nachrichtenstrom": "MessageStream",
    "Parametergrenze": "ParameterOutOfRange",
    "Parameterunbekannt": "UnknownParameter",
    "PasskeyFehler": "PasskeyError",
    "Regelparameter": "ControlParameters",
    "RegelparameterAntwort": "ControlParametersResponse",
    "RegelparameterSchreiben": "WriteControlParameters",
    "ParameterSchreiben": "WriteParameter",
    "Parameterbeschreibung": "ParameterDescription",
    "Schaltergebnis": "SwitchResult",
    "Schaltpunktentwurf": "SchedulePointDraft",
    "ScharfSchalten": "SetArmed",
    "Schnittstelle": "Interface",
    "Sollwert": "Setpoint",
    "SollwertAntwort": "SetpointResponse",
    "SollwertEintrag": "SetpointEntry",
    "SollwerteSchreiben": "WriteSetpoints",
    "SteuerungAntwort": "ControlResponse",
    "Steuerungsfehler": "ControlError",
    "Stoerungsmeldung": "FaultNotice",
    "Tagesabschnitt": "DaySegment",
    "Tageswert": "DayValue",
    "TokenAntwort": "TokenResponse",
    "UebersteuerungAnlegen": "CreateOverride",
    "UebersteuerungAntwort": "OverrideResponse",
    "Veroeffentlichungsstand": "PublicationState",
    "Verwaltungsfehler": "AdministrationError",
    "WebAuthnGeraet": "WebAuthnDevice",
    "Zeitplanfehler": "ScheduleError",
    "ZeitplanpunktAnlegen": "CreateSchedulePoint",
    "ZeitplanpunktAntwort": "SchedulePointResponse",
    "ZeitplanpunktVerschieben": "MoveSchedulePoint",
    "ZoneAntwort": "ZoneResponse",
    "ZoneSchreiben": "WriteZone",
    "Zonenabhaengigkeiten": "ZoneDependencies",
    "Zonenbild": "ZonePicture",
    "ZonennameVergeben": "ZoneNameTaken",
    "Zonenstatistik": "ZoneStatistics",
    "ZonenzustandAntwort": "ZoneStateResponse",
    "ZuordnungBereitsVorhanden": "AssignmentAlreadyExists",
    "Zuschnitt": "TopicCut",
    "ZustandsTopics": "StateTopics",
    "Boost": "Boost",
    "Befund": "Finding",
    "Angabe": "Detail",
    "Zonenbild": "ZonePicture",
    "_Antwort": "_Response",
    "_HaengenderStrom": "_HangingStream",
    "_Liste": "_List",
    "_McpServer": "_McpServer",
    "_Nachschlage": "_Lookup",
    "_Sitzungen": "_Sessions",
}

# Namen aus fremden Bibliotheken und dem Datenbankschema. Sie sehen deutsch aus oder
# treffen zufaellig einen Stamm -- angefasst werden duerfen sie nicht.
FREMD = {
    "ZoneInfo", "Zone", "ZoneDevice", "ZoneOverride", "ZoneSetpoint", "ZoneState",
    "SetpointMode", "OperatingMode", "SensorStatus", "ActorSource", "Integration",
    "Device", "DeviceCapability", "DeviceCapabilityLink", "DeviceRole", "DeviceHealth",
    "Measurement", "SchedulePoint", "ShadowDecision", "Setting", "AuditEvent",
    "ControllerBinding", "ControllerCommand", "Permission", "GroupPermission",
    "AccessGroup", "ApiToken", "ApiTokenPermission", "SetupToken", "Session",
    "User", "UserAccessGroup", "UserPasskey", "PasskeyChallenge", "Base",
}

# Die Reste, die sich nicht zusammensetzen lassen.
EINZELN.update({
    "BEFEHL": "COMMAND", "BEISPIELGRUPPEN": "EXAMPLE_GROUPS",
    "BETRIEBSARTEN": "OPERATING_MODES", "ERREICHBARKEIT": "AVAILABILITY",
    "GERAETELISTE": "DEVICE_LIST", "GERAETEZUSTAND": "DEVICE_STATE",
    "GRUND_CODE_FENSTER_OFFEN": "REASON_CODE_WINDOW_OPEN",
    "GRUND_CODE_UNVERAENDERT": "REASON_CODE_UNCHANGED",
    "GRUND_CODE_FROSTSCHUTZ_SENSORAUSFALL": "REASON_CODE_FROST_SENSOR_FAILURE",
    "GRUND_CODE_GESPERRT_MINDESTDAUER": "REASON_CODE_BLOCKED_MINIMUM_DURATION",
    "GRUND_CODE_KEINE_QUELLE": "REASON_CODE_NO_SOURCE",
    "MESSQUELLE": "TEMPERATURE_SOURCE", "RECHTEBEREICHE": "PERMISSION_AREAS",
    "ZonennameVergeben": "ZoneNameTaken",
    "_erreichbarkeit_verarbeiten": "_process_availability",
    "_fachfehler": "_domain_error", "_geloeschte_abmelden": "_deregister_deleted",
    "_modusformular": "_mode_form", "_sollwertantworten": "_setpoint_responses",
    "_steuerungsantwort": "_control_response",
    "_tastendruck_ausfuehren": "_execute_button_press",
    "_werkzeuge_registrieren": "_register_tools",
    "_zeitplanantworten": "_schedule_responses",
    "aendern": "update", "aktoren_modul": "actuators_module", "anlegen": "create",
    "anmeldung_abschliessen": "finish_authentication",
    "anmeldung_argumente": "authentication_options",
    "anmeldung_beginnen": "begin_authentication",
    "anmeldung_pruefen": "verify_authentication",
    "discovery_nutzlast": "discovery_payload",
    "formular_erneut": "form_again", "_formular_erneut": "_form_again",
    "mcp_trockenlauf_erzwingen": "mcp_force_dry_run",
    "passwort_formularfehler": "password_form_error",
    "sitzung_anlegen": "create_session", "sitzung_aufloesen": "resolve_session",
    "sitzung_widerrufen": "revoke_session",
    "steuerung_scharfschalten": "control_set_armed",
    "veroeffentlichungszyklus": "publication_cycle",
    "ERFORDERLICHE_FAEHIGKEIT": "REQUIRED_CAPABILITY",
    "FELD_ZU_FAEHIGKEIT": "FIELD_TO_CAPABILITY",
    "_FAEHIGKEIT_NACH_MERKMAL": "_CAPABILITY_BY_FEATURE",
    "KEINE_QUELLE": "NO_SOURCE", "ALLE_RECHTE": "ALL_PERMISSIONS",
    "EINGEBAUTE_MODI": "BUILTIN_MODES",
    "_RECHTE_AUS_DEM_MODELL": "_PERMISSIONS_FROM_THE_MODEL",
    "_SCHATTENINTERVALL_STANDARD_S": "_SHADOW_INTERVAL_DEFAULT_S",
    "_STANDARDFELDER": "_DEFAULT_FIELDS",
    "STUMM_OHNE_VORGABEN_SEKUNDEN": "SILENT_WITHOUT_DEFAULTS_SECONDS",
    "GESEHENE_AKTIONEN": "SEEN_ACTIONS",
    "BATTERIE_SCHWACH_PROZENT": "BATTERY_LOW_PERCENT",
    "FUNK_SCHWACH_LQI": "RADIO_WEAK_LQI",
    "OHNE_KAERTCHEN": "WITHOUT_CHIP",
    "TROCKENLAUF_ZUSATZ": "DRY_RUN_SUFFIX",
    "PARAMETER": "PARAMETERS", "NACH_NAME": "BY_NAME",
})

# Die ORM-Attribute tragen die Spaltennamen. Wer sie umbenennt, laesst SQLAlchemy
# nach einer Spalte suchen, die es nicht gibt -- und mypy sieht davon nichts.
SPALTEN = ['PERMISSIONS', '__table_args__', '__tablename__', 'access_group_id', 'action', 'action_code', 'actor_token_id', 'actor_user_id', 'api_token_id', 'availability', 'battery_percent', 'bezeichnung', 'cancelled_at', 'capability_id', 'challenge', 'code', 'command_id', 'consumed_at', 'control_armed', 'created_at', 'created_by_token_id', 'created_by_user_id', 'credential_id', 'decided_at', 'default_hysteresis_k', 'default_min_off_seconds', 'default_min_on_seconds', 'default_sensor_timeout_seconds', 'default_window_resume_delay_seconds', 'description', 'detail', 'device_id', 'device_role_id', 'display_name', 'ends_at', 'expires_at', 'external_id', 'first_seen_at', 'frost_protection_mode_id', 'hysteresis_k', 'id', 'integration_id', 'ip_address', 'is_active', 'is_builtin', 'is_enabled', 'is_group', 'is_zone_scoped', 'label', 'last_login_at', 'last_payload_at', 'last_seen_at', 'last_used_at', 'link_quality', 'measured_at', 'measurement_retention_days', 'min_off_seconds', 'min_on_seconds', 'minute_of_day', 'model', 'name', 'object_id', 'object_type', 'occurred_at', 'operating_mode', 'operating_mode_id', 'outcome_code', 'password_hash', 'payload_count', 'permission_id', 'polling_interval_seconds', 'prefix', 'previous_would_heat', 'public_key', 'reason', 'received_at', 'revoked_at', 'sensor_status_id', 'sensor_timeout_seconds', 'session_lifetime_seconds', 'setpoint_c', 'setpoint_mode_id', 'setpoint_reason', 'shadow_interval_seconds', 'sign_count', 'sort_order', 'source_id', 'starts_at', 'step_k', 'summary', 'temperature_c', 'temperature_offset_k', 'temperature_source_device_id', 'timezone', 'token_hash', 'updated_at', 'user_agent', 'user_id', 'username', 'value_numeric', 'value_text', 'weekday', 'window_open', 'window_resume_delay_seconds', 'would_heat', 'zeremonie', 'zone_id']
FREMD |= set(SPALTEN)

# Die neun Faelle, in denen Adapter und Domaene auf denselben Namen fielen. Das Projekt
# kennt dafuer schon eine Form (`geraet_zuordnen_view`): Die Domaenenfunktion heisst wie
# die Sache, die Ansicht traegt `_view`.
EINZELN.update({
    "zone_anlegen": "create_zone", "zone_erstellen": "create_zone_view",
    "zeitplanpunkt_anlegen": "create_schedule_point",
    "zeitplanpunkt_erstellen": "create_schedule_point_view",
    "modus_anlegen": "create_mode", "modus_erstellen": "create_mode_view",
    "uebersteuerung_anlegen": "create_override",
    "uebersteuerung_erstellen": "create_override_view",
    "scharf_schalten": "arm", "scharfschalten": "arm_view",
    "zonen": "zone_list",
    # `bezeichnung` ist eine Spalte (user_passkey) und bleibt; das gleichnamige
    # Argument der Passkey-Funktionen bleibt damit ebenfalls, sonst liefe es auseinander.
})

# Nach den Staemmen: deutsche Bindeglieder, Pluralreste und Silben, die uebrigbleiben.
NACHBESSERN: list[tuple[str, str]] = [
    ("_mit_", "_with_"), ("_ohne_", "_without_"), ("_oder_", "_or_"),
    ("_und_", "_and_"), ("_je_", "_per_"), ("_fuer_", "_for_"), ("_aus_", "_from_"),
    ("_nach_", "_by_"), ("_in_worten", "_in_words"), ("_der_", "_the_"),
    ("_dem_", "_the_"), ("_des_", "_the_"), ("_ganze_", "_whole_"),
    ("permissionen", "permissions"), ("permissione", "permissions"),
    ("setpointe", "setpoints"), ("modee", "modes"), ("zonee", "zones"),
    ("devicee", "devices"), ("commande", "commands"), ("statee", "states"),
    ("sourcee", "sources"), ("capabilitye", "capabilities"),
    ("assignmenten", "assignments"), ("messagen", "messages"),
    ("readingen", "readings"), ("pointe", "points"), ("groupn", "groups"),
    ("usern", "users"), ("entryen", "entries"), ("commands_topics", "command_topics"),
    ("seite", "page"), ("lauf", "run"), ("aufbewahrung", "retention"),
    ("_neu", "_new"), ("neu_", "new_"), ("domaene_", "domain_"),
    ("abhaengigkeiten", "dependencies"), ("meldung", "notice"),
    ("_entwurf", "_draft"), ("stunden", "hours"), ("minuten", "minutes"),
    ("sekunden", "seconds"), ("_sperre", "_guard"), ("_geheimnis", "_secret"),
    ("_schleife", "_loop"), ("_umgebung", "_environment"), ("_verweise", "_links"),
    ("_bereich", "_area"), ("_stufe", "_stage"), ("_vorrat", "_pool"),
    ("_hinweis", "_hint"), ("_verlauf", "_history"), ("_abweichung", "_deviation"),
    ("_klasse", "_class"), ("_merkmal", "_feature"), ("_zahl", "_number"),
    ("_richtung", "_direction"), ("_ziel", "_target"), ("_rolle", "_role"),
    ("_datei", "_file"), ("_pfad", "_path"), ("_zeile", "_row"), ("_spalte", "_column"),
]

# Verben, die im Deutschen hinten stehen und im Englischen vorne. Wird nach den
# Staemmen angewandt: `device_swap` -> `swap_device`.
VORANSTELLEN = {
    "create", "save", "update", "delete", "remove", "set", "read", "check", "list",
    "process", "move", "adopt", "execute", "deregister", "register", "explain",
    "cancel", "end", "swap", "detach", "assign", "advance", "edit", "show",
    "revoke", "finish", "begin", "resolve", "grant", "force", "send", "publish",
}
