"""Zonen, Sollwert-Modi und Sollwerte

Revision ID: 7368ebcce80f
Revises: 3685e30419a4
Create Date: 2026-08-28 18:36:11.593695

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7368ebcce80f"
down_revision: str | Sequence[str] | None = "3685e30419a4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setpoint_mode",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setpoint_mode")),
        sa.UniqueConstraint("code", name=op.f("uq_setpoint_mode_code")),
    )
    op.create_table(
        "zone",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("operating_mode_id", sa.Integer(), nullable=False),
        sa.Column("temperature_source_device_id", sa.Integer(), nullable=True),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("hysteresis_k", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("min_on_seconds", sa.Integer(), nullable=True),
        sa.Column("min_off_seconds", sa.Integer(), nullable=True),
        sa.Column("sensor_timeout_seconds", sa.Integer(), nullable=True),
        sa.Column("temperature_offset_k", sa.Numeric(precision=4, scale=2), nullable=True),
        sa.Column("window_resume_delay_seconds", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["operating_mode_id"],
            ["operating_mode.id"],
            name=op.f("fk_zone_operating_mode_id_operating_mode"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone")),
        sa.UniqueConstraint("name", name=op.f("uq_zone_name")),
    )
    op.create_table(
        "zone_setpoint",
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("setpoint_mode_id", sa.Integer(), nullable=False),
        sa.Column("temperature_c", sa.Numeric(precision=4, scale=1), nullable=False),
        sa.ForeignKeyConstraint(
            ["setpoint_mode_id"],
            ["setpoint_mode.id"],
            name=op.f("fk_zone_setpoint_setpoint_mode_id_setpoint_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_zone_setpoint_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("zone_id", "setpoint_mode_id", name=op.f("pk_zone_setpoint")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zone_setpoint")
    op.drop_table("zone")
    op.drop_table("setpoint_mode")
    # ### end Alembic commands ###
