"""Uebersteuerungen

Revision ID: c57adf545ef1
Revises: 7368ebcce80f
Create Date: 2026-08-28 19:00:58.304299

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c57adf545ef1"
down_revision: str | Sequence[str] | None = "138ae8f80142"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zone_override",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("setpoint_mode_id", sa.Integer(), nullable=True),
        sa.Column("temperature_c", sa.Numeric(precision=4, scale=1), nullable=True),
        sa.Column("starts_at", sa.DateTime(), nullable=False),
        sa.Column("ends_at", sa.DateTime(), nullable=True),
        sa.Column("cancelled_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("created_by_token_id", sa.Integer(), nullable=True),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "(setpoint_mode_id IS NULL) <> (temperature_c IS NULL)",
            name=op.f("ck_zone_override_entweder_modus_oder_temperatur"),
        ),
        sa.ForeignKeyConstraint(
            ["setpoint_mode_id"],
            ["setpoint_mode.id"],
            name=op.f("fk_zone_override_setpoint_mode_id_setpoint_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["actor_source.id"], name=op.f("fk_zone_override_source_id_actor_source")
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_zone_override_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_override")),
    )
    with op.batch_alter_table("zone_override", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_zone_override_zone_id"), ["zone_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zone_override")
    # ### end Alembic commands ###
