"""Zugaenge, Einstellungen und Audit

Revision ID: 4d43756aecd3
Revises: 4a1c9133a8e0
Create Date: 2026-08-28 19:16:16.489599

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4d43756aecd3"
down_revision: str | Sequence[str] | None = "4a1c9133a8e0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "setup_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("consumed_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setup_token")),
    )
    op.create_table(
        "api_token",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("prefix", sa.String(length=16), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_api_token_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_token")),
        sa.UniqueConstraint("prefix", name=op.f("uq_api_token_prefix")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_api_token_token_hash")),
    )
    op.create_table(
        "session",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["user.id"], name=op.f("fk_session_user_id_user"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_session")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_session_token_hash")),
    )
    op.create_table(
        "setting",
        # autoincrement=False ist hier Pflicht: MariaDB vergibt sonst AUTO_INCREMENT und
        # verbietet dann jede CHECK-Bedingung auf derselben Spalte (Fehler 1901).
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("polling_interval_seconds", sa.Integer(), nullable=False),
        sa.Column("default_hysteresis_k", sa.Numeric(precision=4, scale=2), nullable=False),
        sa.Column("default_min_on_seconds", sa.Integer(), nullable=False),
        sa.Column("default_min_off_seconds", sa.Integer(), nullable=False),
        sa.Column("default_sensor_timeout_seconds", sa.Integer(), nullable=False),
        sa.Column("default_window_resume_delay_seconds", sa.Integer(), nullable=False),
        sa.Column("frost_protection_mode_id", sa.Integer(), nullable=False),
        sa.Column("session_lifetime_seconds", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("id = 1", name=op.f("ck_setting_genau_eine_zeile")),
        sa.ForeignKeyConstraint(
            ["frost_protection_mode_id"],
            ["setpoint_mode.id"],
            name=op.f("fk_setting_frost_protection_mode_id_setpoint_mode"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_setting")),
    )
    op.create_table(
        "audit_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("actor_user_id", sa.Integer(), nullable=True),
        sa.Column("actor_token_id", sa.Integer(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("object_type", sa.String(length=64), nullable=False),
        sa.Column("object_id", sa.String(length=64), nullable=True),
        sa.Column("summary", sa.String(length=255), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["actor_token_id"],
            ["api_token.id"],
            name=op.f("fk_audit_event_actor_token_id_api_token"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["user.id"],
            name=op.f("fk_audit_event_actor_user_id_user"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["actor_source.id"], name=op.f("fk_audit_event_source_id_actor_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_event")),
    )
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_audit_event_occurred_at"), ["occurred_at"], unique=False
        )

    op.create_table(
        "api_token_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("api_token_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["api_token_id"],
            ["api_token.id"],
            name=op.f("fk_api_token_permission_api_token_id_api_token"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_api_token_permission_permission_id_permission"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_api_token_permission_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_api_token_permission")),
        sa.UniqueConstraint("api_token_id", "permission_id", "zone_id", name="recht_je_token"),
    )
    with op.batch_alter_table("zone_override", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_zone_override_created_by_user_id_user"),
            "user",
            ["created_by_user_id"],
            ["id"],
            ondelete="SET NULL",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_zone_override_created_by_token_id_api_token"),
            "api_token",
            ["created_by_token_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("zone_override", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_zone_override_created_by_token_id_api_token"), type_="foreignkey"
        )
        batch_op.drop_constraint(
            batch_op.f("fk_zone_override_created_by_user_id_user"), type_="foreignkey"
        )

    op.drop_table("api_token_permission")
    with op.batch_alter_table("audit_event", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_event_occurred_at"))

    op.drop_table("audit_event")
    op.drop_table("setting")
    op.drop_table("session")
    op.drop_table("api_token")
    op.drop_table("setup_token")
    # ### end Alembic commands ###
