"""Schaltpunkte

Revision ID: 138ae8f80142
Revises: 7368ebcce80f
Create Date: 2026-08-28 18:53:45.144955

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "138ae8f80142"
down_revision: str | Sequence[str] | None = "7368ebcce80f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "schedule_point",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("weekday", sa.Integer(), nullable=False),
        sa.Column("minute_of_day", sa.Integer(), nullable=False),
        sa.Column("setpoint_mode_id", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "minute_of_day BETWEEN 0 AND 1439", name=op.f("ck_schedule_point_minute_im_tag")
        ),
        sa.CheckConstraint(
            "weekday BETWEEN 1 AND 7", name=op.f("ck_schedule_point_wochentag_1_bis_7")
        ),
        sa.ForeignKeyConstraint(
            ["setpoint_mode_id"],
            ["setpoint_mode.id"],
            name=op.f("fk_schedule_point_setpoint_mode_id_setpoint_mode"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_schedule_point_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_schedule_point")),
        sa.UniqueConstraint("zone_id", "weekday", "minute_of_day", name="zeitpunkt_je_zone"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_point")
    # ### end Alembic commands ###
