"""Nachschlagetabellen

Revision ID: 3685e30419a4
Revises: 6d4bb757dca0
Create Date: 2026-08-28 18:19:06.733560

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

from thermoctl.db.models.lookup import (
    ACTOR_SOURCES,
    DEVICE_CAPABILITIES,
    DEVICE_ROLES,
    INTEGRATIONS,
    OPERATING_MODES,
    PERMISSIONS,
)


# revision identifiers, used by Alembic.
revision: str = '3685e30419a4'
down_revision: str | Sequence[str] | None = '6d4bb757dca0'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _fuellen(tabellenname: str, zeilen: list[tuple[str, str]]) -> None:
    op.bulk_insert(
        sa.table(
            tabellenname,
            sa.column("code", sa.String),
            sa.column("label", sa.String),
        ),
        [{"code": c, "label": b} for c, b in zeilen],
    )


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor_source',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_actor_source')),
    sa.UniqueConstraint('code', name=op.f('uq_actor_source_code'))
    )
    op.create_table('device_capability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_capability')),
    sa.UniqueConstraint('code', name=op.f('uq_device_capability_code'))
    )
    op.create_table('device_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_device_role')),
    sa.UniqueConstraint('code', name=op.f('uq_device_role_code'))
    )
    op.create_table('integration',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_integration')),
    sa.UniqueConstraint('code', name=op.f('uq_integration_code'))
    )
    op.create_table('operating_mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operating_mode')),
    sa.UniqueConstraint('code', name=op.f('uq_operating_mode_code'))
    )
    op.create_table('permission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('is_zone_scoped', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permission')),
    sa.UniqueConstraint('code', name=op.f('uq_permission_code'))
    )
    # ### end Alembic commands ###
    _fuellen("operating_mode", OPERATING_MODES)
    _fuellen("integration", INTEGRATIONS)
    # Historische Migrationen müssen reproduzierbar bleiben, auch wenn die zentrale
    # Liste später erweitert wird. Teilprojekt 2 fügt seine Codes in eigener Revision ein.
    _fuellen("device_capability", DEVICE_CAPABILITIES[:5])
    _fuellen("device_role", DEVICE_ROLES)
    _fuellen("actor_source", ACTOR_SOURCES)
    op.bulk_insert(
        sa.table(
            "permission",
            sa.column("code", sa.String),
            sa.column("description", sa.String),
            sa.column("is_zone_scoped", sa.Boolean),
        ),
        [
            # Geschnitten wie DEVICE_CAPABILITIES daneben: Diese Revision muss den
            # Stand von damals einspielen, auch wenn die zentrale Liste später
            # wächst. Sonst legt sie auf einer frischen Datenbank Codes an, die eine
            # spätere Revision noch einmal einfügen will.
            {"code": c, "description": d, "is_zone_scoped": z}
            for c, d, z in PERMISSIONS[:15]
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('permission')
    op.drop_table('operating_mode')
    op.drop_table('integration')
    op.drop_table('device_role')
    op.drop_table('device_capability')
    op.drop_table('actor_source')
    # ### end Alembic commands ###
