"""Benutzer, Gruppen und Rechtezuordnung

Revision ID: 4a1c9133a8e0
Revises: 7368ebcce80f
Create Date: 2026-08-28 18:54:20.837648

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "4a1c9133a8e0"
down_revision: str | Sequence[str] | None = "f41afdb84b2a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "access_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=True),
        sa.Column("is_builtin", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_access_group")),
        sa.UniqueConstraint("name", name=op.f("uq_access_group_name")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("username", name=op.f("uq_user_username")),
    )
    op.create_table(
        "user_access_group",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("access_group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["access_group.id"],
            name=op.f("fk_user_access_group_access_group_id_access_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
            name=op.f("fk_user_access_group_user_id_user"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "access_group_id", name=op.f("pk_user_access_group")),
    )
    op.create_table(
        "group_permission",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("access_group_id", sa.Integer(), nullable=False),
        sa.Column("permission_id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["access_group_id"],
            ["access_group.id"],
            name=op.f("fk_group_permission_access_group_id_access_group"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["permission_id"],
            ["permission.id"],
            name=op.f("fk_group_permission_permission_id_permission"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"],
            ["zone.id"],
            name=op.f("fk_group_permission_zone_id_zone"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_group_permission")),
        sa.UniqueConstraint(
            "access_group_id", "permission_id", "zone_id", name="recht_je_gruppe_und_zone"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("group_permission")
    op.drop_table("user_access_group")
    op.drop_table("user")
    op.drop_table("access_group")
    # ### end Alembic commands ###
