"""Geraete, Faehigkeiten und Zuordnungen

Revision ID: f41afdb84b2a
Revises: 7368ebcce80f
Create Date: 2026-08-28 18:53:57.216107

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f41afdb84b2a"
down_revision: str | Sequence[str] | None = "c57adf545ef1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("integration_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=191), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("first_seen_at", sa.DateTime(), nullable=True),
        sa.Column("last_seen_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["integration_id"],
            ["integration.id"],
            name=op.f("fk_device_integration_id_integration"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_device")),
        sa.UniqueConstraint("integration_id", "external_id", name="adresse_je_anbindung"),
    )
    op.create_table(
        "device_capability_link",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("capability_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["capability_id"],
            ["device_capability.id"],
            name=op.f("fk_device_capability_link_capability_id_device_capability"),
        ),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.id"],
            name=op.f("fk_device_capability_link_device_id_device"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "device_id", "capability_id", name=op.f("pk_device_capability_link")
        ),
    )
    op.create_table(
        "zone_device",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zone_id", sa.Integer(), nullable=False),
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("device_role_id", sa.Integer(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["device_id"], ["device.id"], name=op.f("fk_zone_device_device_id_device")
        ),
        sa.ForeignKeyConstraint(
            ["device_role_id"],
            ["device_role.id"],
            name=op.f("fk_zone_device_device_role_id_device_role"),
        ),
        sa.ForeignKeyConstraint(
            ["zone_id"], ["zone.id"], name=op.f("fk_zone_device_zone_id_zone"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_zone_device")),
        sa.UniqueConstraint("zone_id", "device_id", "device_role_id", name="rolle_je_zuordnung"),
    )
    with op.batch_alter_table("zone", schema=None) as batch_op:
        batch_op.create_foreign_key(
            batch_op.f("fk_zone_temperature_source_device_id_device"),
            "device",
            ["temperature_source_device_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("zone", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_zone_temperature_source_device_id_device"), type_="foreignkey"
        )

    op.drop_table("zone_device")
    op.drop_table("device_capability_link")
    op.drop_table("device")
    # ### end Alembic commands ###
